name: Node.js Build
# hhee
# Trigger the workflow on specific events
on:
  push:
    branches:
      - main

# Define the jobs to run in the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run build script (if you have one)
      - name: Build the project
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Debug file structure
        run: ls -la
         # Step 5: Run tests (if you have tests configured)
      - name: Run tests
        run: npm test --detectOpenHandles
    
